clients/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required, permission_required

app_name = 'clients'
urlpatterns = [
	path('', views.clientList.as_view(), name='clientList'),
	path('<int:pk>/', login_required(views.DetailView.as_view()) , name='detail'),
	path('update/<int:pk>/', permission_required('clients.change_client')(views.UpdateView.as_view()), name='update'),
	path('clientCreate/', views.CreateView.as_view(), name='create'),
	path('clientDelete/<int:pk>/', views.DeleteView.as_view(), name='deleteClient'),
	path('<int:pk>/dealsCreate/', views.dealsCreateView.as_view(), name='dealsCreate'),
	path('<int:pk>/taskCreate/', views.taskCreateView.as_view(), name='taskCreateView'),
]

deals/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'deals'
urlpatterns = [
	path('', views.DealsListView.as_view(), name='dealsList'),
	path('<int:pk>/', views.DealsDetailView.as_view(), name='DealsDetailView'),
	path('<int:pk>/updateDeal/', views.DealsUpdateView.as_view(), name='DealsUpdateView'),
	path('<int:pk>/deleteDeal/', views.DealsDeleteView.as_view(), name='DealsDeleteView'),
]

employees/urls.py
from django.urls import path
from . import views

app_name = 'employees'
urlpatterns = [
    path('', views.IndexView.as_view(), name='employeeList'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/editEmployee', views.UpdateView.as_view(), name='update'),
    path('employeeCreate/', views.CreateView.as_view(), name='create'),
    path('<int:pk>/delete/', views.DeleteView.as_view(), name='delete'),
]

indexapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

mycrm/urls.py
from django.contrib import admin
from django.urls import path, include
from clients import views as client_views
from employees import views as employee_views
from deals import views as deals_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('indexapp.urls')),
    path('clientList/', include('clients.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('clientCreate/', client_views.CreateView),
    path('clientDelete/', client_views.DeleteView),
    path('employeeList/', include('employees.urls')),
    path('detail/<int:pk>/', employee_views.DetailView),
    path('edit/<int:pk>/', employee_views.UpdateView),
    path('employeeCreate/', employee_views.CreateView),
    path('delete/<int:pk>/', employee_views.DeleteView),
    path('dealsList/', include('deals.urls')),
    path('taskList/', include('task_manager.urls')),
]

task_manager/urls.py
from django.urls import path
from . import views

app_name = 'tasks'
urlpatterns = [
	path('', views.TaskList.as_view(), name='taskList'),
	path('<int:pk>', views.TaskDetail.as_view(), name='taskDetail'),
	path('<int:pk>/edit', views.TaskEdit.as_view(), name='taskEdit'),
	path('<int:pk>/confirmDelete', views.TaskDelete.as_view(), name='taskDelete'),
]

indexapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'indexapp/index.html')

templates/indexapp/index.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Welcome</title>
</head>
<body class="indexPage">
	<h2>Welcome to Paul's CRM</h2>
	<br>
	<div class="jumbotron">
  	<h1 class="display-4">This is not all that complicated</h1>
  	<p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  	<hr class="my-4">
  	<p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  	<a href="{% url 'clients:clientList' %}" class="btn btn-dark">View Client List</a>
    <a href="{% url 'clients:create' %}" class="btn btn-dark">Add Client</a>
    <a href="{% url 'employees:employeeList' %}" class="btn btn-dark">View Employees</a>
    <a href="{% url 'employees:create' %}" class="btn btn-dark">Create Employee</a><br><br>
    <a href="{% url 'deals:dealsList' %}" class="btn btn-dark"> View Deals</a>
    <a href="{% url 'tasks:taskList' %}" class="btn btn-dark">Task List</a>
  </div>

	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.bundle.min.js" integrity="sha384-pjaaA8dDz/5BgdFUPX6M/9SUZv4d12SUPF0axWc+VRZkx5xU3daN+lYb49+Ax+Tl" crossorigin="anonymous"></script>
</body>
</html>