clients/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required, permission_required

app_name = 'clients'
urlpatterns = [
	path('', views.clientList.as_view(), name='clientList'),
	path('<int:pk>/', login_required(views.DetailView.as_view()) , name='detail'),
	path('update/<int:pk>/', permission_required('clients.change_client')(views.UpdateView.as_view()), name='update'),
	path('clientCreate/', views.CreateView.as_view(), name='create'),
	path('clientDelete/<int:pk>/', views.DeleteView.as_view(), name='deleteClient'),
	path('<int:pk>/dealsCreate/', views.dealsCreateView.as_view(), name='dealsCreate'),
	path('<int:pk>/taskCreate/', views.taskCreateView.as_view(), name='taskCreateView'),
]

deals/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'deals'
urlpatterns = [
	path('', views.DealsListView.as_view(), name='dealsList'),
	path('<int:pk>/', views.DealsDetailView.as_view(), name='DealsDetailView'),
	path('<int:pk>/updateDeal/', views.DealsUpdateView.as_view(), name='DealsUpdateView'),
	path('<int:pk>/deleteDeal/', views.DealsDeleteView.as_view(), name='DealsDeleteView'),
]

mycrm/urls.py
from django.contrib import admin
from django.urls import path, include
from clients import views as client_views
from employees import views as employee_views
from deals import views as deals_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('indexapp.urls')),
    path('clientList/', include('clients.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('clientCreate/', client_views.CreateView),
    path('clientDelete/', client_views.DeleteView),
    path('employeeList/', include('employees.urls')),
    path('detail/<int:pk>/', employee_views.DetailView),
    path('edit/<int:pk>/', employee_views.UpdateView),
    path('employeeCreate/', employee_views.CreateView),
    path('delete/<int:pk>/', employee_views.DeleteView),
    path('dealsList/', include('deals.urls')),
    path('taskList/', include('task_manager.urls')),
]

task_manager/urls.py
from django.urls import path
from . import views

app_name = 'tasks'
urlpatterns = [
	path('', views.TaskList.as_view(), name='taskList'),
	path('<int:pk>', views.TaskDetail.as_view(), name='taskDetail'),
	path('<int:pk>/edit', views.TaskEdit.as_view(), name='taskEdit'),
	path('<int:pk>/confirmDelete', views.TaskDelete.as_view(), name='taskDelete'),
]

clients/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Client (models.Model):
    id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=80, blank=True)
    last_name = models.CharField(max_length=80, blank=True)
    address_1 = models.CharField(max_length=150, blank=True)
    address_2 = models.CharField(max_length=150, blank=True)
    city = models.CharField(max_length=30, blank=True)
    state = models.CharField(max_length=30, blank=True)
    zipcode = models.CharField(max_length=30, blank=True)
    phone_1 = models.CharField(max_length=30, blank=True)
    phone_2 = models.CharField(max_length=30, blank=True)
    phone_3 = models.CharField(max_length=30, blank=True)
    phone_4 = models.CharField(max_length=30, blank=True)
    dob = models.CharField(max_length=30, blank=True)
    ssn = models.CharField(max_length=30, blank=True)
    notes = models.CharField(max_length=400, blank=True)

    def __str__(self):
        template = '{0.last_name} {0.first_name}'
        return template.format(self)
        

clients/forms.py
from django import forms
from .models import Client

class createForm(forms.ModelForm):
	first_name = forms.CharField(max_length=80, required=False)
	last_name = forms.CharField(max_length=80, required=False)
	address_1 = forms.CharField(max_length=150, required=False)
	address_2 = forms.CharField(max_length=150, required=False)
	city = forms.CharField(max_length=30, required=False)
	state = forms.CharField(max_length=30, required=False)
	zipcode = forms.CharField(max_length=30, required=False)
	phone_1 = forms.CharField(max_length=30, required=False)
	phone_2 = forms.CharField(max_length=30, required=False)
	phone_3 = forms.CharField(max_length=30, required=False)
	phone_4 = forms.CharField(max_length=30, required=False)
	dob = forms.CharField(max_length=30, required=False)
	ssn = forms.CharField(max_length=30, required=False)
	notes = forms.CharField(max_length=400, required=False)
	
	class Meta:
		model = Client
		fields = '__all__'
	

clients/views.py
from .models import Client
from deals.models import Deals
from task_manager.models import Tasks
from django.views import generic
from django.urls import reverse
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin

# Create your views here.
class clientList(LoginRequiredMixin, generic.ListView):
	template_name = 'clients/clientList.html'
	context_object_name = 'clients'
	paginate_by = 25

	def get_queryset(self):
		if self.request.method == 'GET' and self.request.GET:
			if 'id' in self.request.GET:
				if self.request.GET['id']:
					searchtxt = self.request.GET.get('id', None)
					return Client.objects.filter(id__icontains=searchtxt)

				if self.request.GET['last_name']:
					searchtxt_2 = self.request.GET.get('last_name', None)
					return Client.objects.filter(last_name__icontains=searchtxt_2)

				else:
					return Client.objects.order_by('id')

		else:
			return Client.objects.order_by('id')
		

class DetailView(LoginRequiredMixin, generic.DetailView):
	model = Client
	template_name = 'clients/clientDetail.html'
	context_object_name = 'client'

	def get_context_data(self, **kwargs):
		    context = super(DetailView, self).get_context_data(**kwargs)
		    #Get slug(client id)
		    cid = self.kwargs['pk']
		    context['deal_list'] = Deals.objects.filter(client_id_id=cid)
		    context['task_list'] = Tasks.objects.filter(client_id=cid)
		    return context


class UpdateView(PermissionRequiredMixin, generic.UpdateView):
	model = Client
	fields = '__all__'
	success_url = '/clientList'
	permission_required = 'clients.change_client'



class CreateView(PermissionRequiredMixin, generic.CreateView):
	model = Client
	fields = '__all__'
	template_name_suffix = '_create_form'
	success_url = '/clientList'
	permission_required = 'clients.add_client'

class DeleteView(PermissionRequiredMixin, generic.DeleteView):
	model = Client
	success_url = '/clientList'
	permission_required = 'clients.delete_client'


class dealsCreateView(PermissionRequiredMixin, generic.CreateView):
	model = Deals
	fields = '__all__'
	template_name_suffix = '_create_form'
	permission_required = 'clients.change_client'
	

	def get_context_data(self, **kwargs):
		context = super(dealsCreateView, self).get_context_data(**kwargs)
		cid = self.kwargs['pk']
		context['cid'] = cid
		context['client'] = Client.objects.get(id=cid)
		return context

	def get_success_url(self, **kwargs):
		return reverse('clients:detail', kwargs = {'pk': self.object.client_id_id})

	

class taskCreateView(PermissionRequiredMixin, generic.CreateView):
	model = Tasks
	fields = '__all__'
	template_name = 'tasks/task_create_form.html'
	permission_required = 'clients.change_client'

	def get_context_data(self, **kwargs):
		context = super(taskCreateView, self).get_context_data(**kwargs)
		cid = self.kwargs['pk']
		context['cid'] = cid
		context['client'] = Client.objects.get(id=cid)

		return context

	def get_success_url(self, **kwargs):
		return reverse('clients:detail', kwargs = {'pk': self.object.client_id_id})

clients/templates/clients/clientDetail.html
{% extends 'basic.html' %}
{% block content %}
	<h1>{{ client.last_name }}, {{ client.first_name }}</h1>
	<div style="background-color: #191924; padding: 50px 25px">
		<div class="container">
		<div class="row">
			
			<div class="col-sm">
				<ul class="list-group">
					<li class="list-group-item">{{ client.first_name }}</li>
					<li class="list-group-item">{{ client.address_1 }}</li>
					<li class="list-group-item">{{ client.city }}</li>
					<li class="list-group-item">{{ client.zipcode }}</li>
					<li class="list-group-item">{{ client.phone_2 }}</li>
					<li class="list-group-item">{{ client.ssn }}</li>
					<li class="list-group-item">{{ client.manager }}</li>
				</ul>
			</div>
			<div class="col-sm">
				<ul class="list-group">
					<li class="list-group-item">{{ client.last_name }}</li>
					<li class="list-group-item">{{ client.address_2 }}</li>
					<li class="list-group-item">{{ client.state }}</li>
					<li class="list-group-item">{{ client.phone_1 }}</li>
					<li class="list-group-item">{{ client.dob }}</li>
					<li class="list-group-item">{{ client.department }}</li>
					<li class="list-group-item">{{ client.salary }}</li>
				</ul>
			</div>
		</div>
		<div class="row">
			<div class="col" style="color: yellow;">
				<ul>
					<h3 style="text-align:left">Deals</h3>
					{% for deal in deal_list %}
						<li><a href="{% url 'deals:DealsDetailView' deal.id %}">{{ deal }}</a></li>
					{% endfor %}
				</ul>
			</div>
			<div class="col" style="color: yellow;">
				<ul>
					<h3 style="text-align:left">Tasks</h3>
					{% for task in task_list %}
						<li><a href="{% url 'tasks:taskDetail' task.id %}">{{ task }}</a></li>
					{% endfor %}
				</ul>
			</div>
		</div>
		<div class="row" style="padding-top: 10px">
			<div class="col-sm">
				
				<a href="{% url 'clients:clientList' %}" class="btn btn-danger">Client List</a>
				<a href="{% url 'clients:update' client.id %}" class="btn btn-danger">Edit</a>
				<a href="{% url 'clients:deleteClient' client.id %}" class="btn btn-danger">Delete</a>
			</div>
			<div class="col-sm">
				<a href="{% url 'clients:dealsCreate' client.id %}" class="btn btn-outline-info">Add Deal</a>
				<a href="{% url 'clients:taskCreateView' client.id %}" class="btn btn-outline-info">Add Task</a>
			</div>
		</div>
	</div>
</div>
{% endblock %}

clients/templates/clients/clientList.html
{% extends 'basic.html' %}
{% load static %}


{% block content %}
	<div class="page-header">
		<h1 style="margin-bottom: 100px">Client List</h1>
		<div class="row">
			<div class="col">
				<a href="{% url 'index' %}" class="btn btn-outline-info" style="margin-bottom: 15px">Home</a>
				<a href="{% url 'clients:clientList' %}" class="btn btn-outline-info" style="margin-bottom: 15px">Full List</a>
			</div>
			<div class="col-lg">
				<form method="GET">
					<input type="textbox" name="last_name" placeholder="Last Name">
					<input type="textbox" name="id" placeholder="Client ID">
					<button type="submit" class="btn btn-outline-danger">Search</button>
				</form>
			</div>
			<div class="col">
				<a href="{% url 'logout' %}" class="btn btn-outline-info float-right">Logout</a>
			</div>
		</div>
	</div>
	<div class="search"></div>
	<table class="table">
		<thead style="color: #F25F5C">
			<tr>
				<th scope="col">Client ID</th>
				<th scope="col">First Name</th>
				<th scope="col">Last Name</th>
				<th scope="col">City</th>
				<th scope="col">State</th>
			</tr>	
		</thead>
		<tbody>
			
			{% for client in clients.all %}
			<tr>
				<th class="row"><a href="{% url 'clients:detail' client.id %}">{{ client.id }}</a></th>
				<td><a href="{% url 'clients:detail' client.id %}">{{ client.first_name }}</a></td>
				<td><a href="{% url 'clients:detail' client.id %}">{{ client.last_name }}</a></td>
				<td><a href="{% url 'clients:detail' client.id %}">{{ client.city }}</a></td>
				<td><a href="{% url 'clients:detail' client.id %}">{{ client.state }}</a></td>
			</tr>
			{% endfor %}
			
		</tbody>
	</table>
{% endblock %}

clients/templates/clients/client_confirm_delete.html
{% extends 'basic.html' %}
{% block content %}
	<form method="POST">
		{% csrf_token %}
		<p style="color: yellow">ARE YOU SURE YOU WANT TO DELETE {{ client.last_name }}, {{ client.first_name }}??</p>
		<button type="submit" class="btn btn-danger">Confirm</button>
		<a href="{% url 'clients:detail' client.id %}" class="btn btn-danger">Cancel</a>
	</form>

	{% endblock %}

clients/templates/clients/client_create_form.html
{% extends 'basic.html' %}

{% block content %}
	<h1>Create a new client!</h1>
		<div class="form-group" style="background: #191924">
			<form method="POST">
				{% csrf_token %}
				<table>
					{% for field in form %}		
						<tr class="row">
							<td class="col">{{ field.label_tag }}</td>
							<td class="col"> {{ field }}</td>
							<td>{{ field.errors }}</td>
						</tr>
					{% endfor %}
				</table>
				<button class="btn btn-danger btn-lg" type="submit">Save</button>
				<a href="{% url 'clients:clientList' %}" class="btn btn-danger">Cancel</a>
			</form>
		</div>
{% endblock %}

clients/templates/clients/client_form.html
{% extends 'basic.html' %}

{% block content %}
	<h1>{{ client.last_name }}, {{ client.first_name }} ID: {{ client.id }}</h1>
		
		<form method="POST" action="">
			{% csrf_token %}
			<div class="form-group" style="background: #191924;">
				<table style="margin: 20px 15px">
				{% for field in form %}		
					<tr class="row">
						<td class="col">{{ field.label_tag }}</td>
						<td class="col"> {{ field }}</td>
						<td>{{ field.errors }}</td>
					</tr>
				{% endfor %}
				</table>
				<button class="btn btn-danger btn-lg" type="submit">Update</button>
			</div>
		</form>
{% endblock %}