deals/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'deals'
urlpatterns = [
	path('', views.DealsListView.as_view(), name='dealsList'),
	path('<int:pk>/', views.DealsDetailView.as_view(), name='DealsDetailView'),
	path('<int:pk>/updateDeal/', views.DealsUpdateView.as_view(), name='DealsUpdateView'),
	path('<int:pk>/deleteDeal/', views.DealsDeleteView.as_view(), name='DealsDeleteView'),
]

mycrm/urls.py
from django.contrib import admin
from django.urls import path, include
from clients import views as client_views
from employees import views as employee_views
from deals import views as deals_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('indexapp.urls')),
    path('clientList/', include('clients.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('clientCreate/', client_views.CreateView),
    path('clientDelete/', client_views.DeleteView),
    path('employeeList/', include('employees.urls')),
    path('detail/<int:pk>/', employee_views.DetailView),
    path('edit/<int:pk>/', employee_views.UpdateView),
    path('employeeCreate/', employee_views.CreateView),
    path('delete/<int:pk>/', employee_views.DeleteView),
    path('dealsList/', include('deals.urls')),
    path('taskList/', include('task_manager.urls')),
]

task_manager/urls.py
from django.urls import path
from . import views

app_name = 'tasks'
urlpatterns = [
	path('', views.TaskList.as_view(), name='taskList'),
	path('<int:pk>', views.TaskDetail.as_view(), name='taskDetail'),
	path('<int:pk>/edit', views.TaskEdit.as_view(), name='taskEdit'),
	path('<int:pk>/confirmDelete', views.TaskDelete.as_view(), name='taskDelete'),
]

task_manager/models.py
from django.db import models
from employees.models import Employee
from clients.models import Client

# Create your models here.
class Tasks(models.Model):
	STATUS_CHOICES = (
			('processing', 'Processing'),
			('completed', 'Completed'),
			('attention', 'Needs Attention'),
			('research', 'Research'),
		)
	id = models.AutoField(primary_key=True)
	client = models.ForeignKey(Client, on_delete=models.PROTECT)
	employee = models.ForeignKey(Employee, on_delete=models.PROTECT)
	status = models.CharField(max_length=100, choices=STATUS_CHOICES)
	department = models.CharField(max_length=100)
	date_created = models.DateField(auto_now=True)
	date_due = models.DateField(auto_now=False)
	summary = models.CharField(max_length=500, blank=True)
	attachment = models.FileField(upload_to='uploads/%y/%m/', blank=True)

	def __str__(self):
	    template = 'Task ID: {0.id} -- Staus: {0.status}'
	    return template.format(self)

task_manager/views.py
from .models import Tasks
from clients.models import Client
from employees.models import Employee
from django.views import generic
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import PermissionRequiredMixin

# Create your views here.
class TaskList(generic.ListView):
	template_name = 'tasks/taskList.html'
	context_object_name = 'tasks'
	paginate_by = 25

	def get_queryset(self):
		if self.request.method == 'GET' and self.request.GET:
			if 'id' in self.request.GET:
				if self.request.GET['id']:
					searchtxt = self.request.GET.get('id', None)
					return Tasks.objects.filter(id__icontains=searchtxt)

				else:
					return Tasks.objects.order_by('id')

		else:
			return Tasks.objects.order_by('id')

class TaskDetail(generic.DetailView):
	model = Tasks
	template_name = 'tasks/taskDetail.html'
	context_object_name = 'task'

	def get_context_data(self, **kwargs):
		context = super(TaskDetail, self).get_context_data(**kwargs)
		context['client'] = get_object_or_404(Client, pk=self.object.client_id)
		context['employee'] = get_object_or_404(Employee, pk=self.object.employee_id)

		return context


class TaskEdit(PermissionRequiredMixin, generic.UpdateView):
	model = Tasks
	fields = '__all__'
	success_url = '/taskList'
	template_name = 'tasks/task_edit_form.html'
	context_object_name = 'task'
	permission_required = 'clients.change_client'


class TaskDelete(PermissionRequiredMixin, generic.DeleteView):
	model = Tasks
	success_url = '/taskList'
	context_object_name = 'task'
	template_name = 'tasks/task_confirm_delete.html'	
	permission_required = 'clients.delete_client'	


		
		

task_manager/templates/tasks/taskDetail.html
{% extends 'basic.html' %}
{% block content %}
	<div style="background-color: #191924; padding: 50px 25px">
		<div class="container">
		<div class="row">
			
			<div class="col-sm">
				<ul class="list-group">
					<li class="list-group-item"><b>Task ID:</b>  {{ task.id }}</li>
					<li class="list-group-item"><b>Client ID:</b>  {{ task.client_id }} | 
						<b>Client Name:</b>{{client.first_name}} {{client.last_name}}</li>
					<li class="list-group-item"><b>Employee ID:</b>  {{ task.employee_id }} | 
						<b>Employee Name: </b> {{employee.first_name}} {{employee.last_name}}</li>
					<li class="list-group-item"><b>Status:</b>  {{ task.status }}</li>
					<li class="list-group-item"><b>Date Started:</b>  {{ task.date_created }}</li>
					<li class="list-group-item"><b>Due Date:</b>  {{ task.date_due }}</li>
					<li class="list-group-item"><b>Notes:</b>  {{ task.summary }}</li>
					<li class="list-group-item"><b>Attachments:</b>  {{ task.attachment }}</li>
				</ul>
			</div>
		</div>
		<div class="row" style="padding-top: 10px">
			<div class="col-sm">
				
				<a href="{% url 'tasks:taskList' %}" class="btn btn-danger">Task List</a>
				<a href="{% url 'tasks:taskEdit' task.id %}" class="btn btn-danger">Edit</a>
				<a href="{% url 'tasks:taskDelete' task.id %}" class="btn btn-danger">Delete</a>
			</div>
		</div>
	</div>
</div>
{% endblock %}

task_manager/templates/tasks/taskList.html
{% extends 'basic.html' %}
{% load static %}


{% block content %}
	<div class="page-header">
		<h1 style="margin-bottom: 100px">Task List</h1>
		<div class="row">
			<div class="col">
				<a href="{% url 'index' %}" class="btn btn-outline-info" style="margin-bottom: 15px">Home</a>
				<a href="" class="btn btn-outline-info" style="margin-bottom: 15px">Full List</a>
			</div>
			<div class="col-lg">
				<form method="GET">
					<input type="textbox" name="id" placeholder="task ID">
					<button type="submit" class="btn btn-outline-danger">Search</button>
				</form>
			</div>
			<div class="col">
				<a href="{% url 'logout' %}" class="btn btn-outline-info float-right">Logout</a>
			</div>
		</div>
	</div>
	<div class="search"></div>
	<table class="table">
		<thead style="color: #F25F5C">
			<tr>
				<th scope="col">Task ID</th>
				<th scope="col">Client ID</th>
				<th scope="col">Employee ID</th>
				<th scope="col">Date Started</th>
				<th scope="col">Date Due</th>
			</tr>	
		</thead>
		<tbody>
			
			{% for task in tasks.all %}
			<tr>
				<th class="row"><a href="{% url 'tasks:taskDetail' task.id %}">{{ task.id }}</a></th>
				<td><a href="{% url 'tasks:taskDetail' task.id %}">{{ task.client_id }}</a></td>
				<td><a href="{% url 'tasks:taskDetail' task.id %}">{{ task.employee_id }}</a></td>
				<td><a href="{% url 'tasks:taskDetail' task.id %}">{{ task.date_created }}</a></td>
				<td><a href="{% url 'tasks:taskDetail' task.id %}">{{ task.date_due }}</a></td>
			</tr>
			{% endfor %}
			
		</tbody>
	</table>
{% endblock %}

task_manager/templates/tasks/task_confirm_delete.html
{% extends 'basic.html' %}
{% block content %}
	<form method="POST">
		{% csrf_token %}
		<p style="color: yellow">ARE YOU SURE YOU WANT TO DELETE THIS TASK??</p>
		<button type="submit" class="btn btn-danger">Confirm</button>
		<a href="{% url 'tasks:taskDetail' task.id %}" class="btn btn-danger">Cancel</a>
	</form>

	{% endblock %}

task_manager/templates/tasks/task_create_form.html
{% extends 'basic.html' %}

{% block content %}
	<h1>Create a new Task!</h1>
		<div class="form-group" style="background: #191924">
			<form method="POST">
				{% csrf_token %}
				<table>
					{% for field in form %}		
						<tr class="row">
							<td class="col">{{ field.label_tag }}</td>
							<td class="col"> {{ field }}</td>
							<td>{{ field.errors }}</td>
						</tr>
					{% endfor %}
				</table>
				<button class="btn btn-danger btn-lg" type="submit">Save</button>
				<a href="{% url 'tasks:taskList' %}" class="btn btn-danger">Cancel</a>
			</form>
		</div>
{% endblock %}

task_manager/templates/tasks/task_edit_form.html
{% extends 'basic.html' %}

{% block content %}
		
		<form method="POST" action="">
			{% csrf_token %}
			<div class="form-group" style="background: #191924;">
				<table style="margin: 20px 15px">
				{% for field in form %}		
					<tr class="row">
						<td class="col">{{ field.label_tag }}</td>
						<td class="col"> {{ field }}</td>
						<td>{{ field.errors }}</td>
					</tr>
				{% endfor %}
				</table>
				<button class="btn btn-danger" type="submit">Update</button>
				<a href="{% url 'tasks:taskDetail' task.id %}" class="btn btn-danger">Back</a>
			</div>
		</form>
{% endblock %}