deals/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'deals'
urlpatterns = [
	path('', views.DealsListView.as_view(), name='dealsList'),
	path('<int:pk>/', views.DealsDetailView.as_view(), name='DealsDetailView'),
	path('<int:pk>/updateDeal/', views.DealsUpdateView.as_view(), name='DealsUpdateView'),
	path('<int:pk>/deleteDeal/', views.DealsDeleteView.as_view(), name='DealsDeleteView'),
]

employees/urls.py
from django.urls import path
from . import views

app_name = 'employees'
urlpatterns = [
    path('', views.IndexView.as_view(), name='employeeList'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/editEmployee', views.UpdateView.as_view(), name='update'),
    path('employeeCreate/', views.CreateView.as_view(), name='create'),
    path('<int:pk>/delete/', views.DeleteView.as_view(), name='delete'),
]

mycrm/urls.py
from django.contrib import admin
from django.urls import path, include
from clients import views as client_views
from employees import views as employee_views
from deals import views as deals_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('indexapp.urls')),
    path('clientList/', include('clients.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('clientCreate/', client_views.CreateView),
    path('clientDelete/', client_views.DeleteView),
    path('employeeList/', include('employees.urls')),
    path('detail/<int:pk>/', employee_views.DetailView),
    path('edit/<int:pk>/', employee_views.UpdateView),
    path('employeeCreate/', employee_views.CreateView),
    path('delete/<int:pk>/', employee_views.DeleteView),
    path('dealsList/', include('deals.urls')),
    path('taskList/', include('task_manager.urls')),
]

employees/models.py
from django.db import models

# Create your models here.
class Employee(models.Model):
    id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=80, blank=True)
    last_name = models.CharField(max_length=80, blank=True)
    address_1 = models.CharField(max_length=150, blank=True)
    address_2 = models.CharField(max_length=150, blank=True)
    city = models.CharField(max_length=30, blank=True)
    state = models.CharField(max_length=2, blank=True)
    zipcode = models.CharField(max_length=10, blank=True)
    phone_1 = models.CharField(max_length=12, blank=True)
    phone_2 = models.CharField(max_length=12, blank=True)
    dob = models.CharField(max_length=12, blank=True)
    ssn = models.CharField(max_length=12, blank=True)
    department = models.CharField(max_length=80, blank=True)
    manager = models.CharField(max_length=80, blank=True)
    salary = models.DecimalField(max_digits=12, decimal_places=2, blank=True)

    def __str__(self):
        template = '{0.last_name} {0.first_name}'
        return template.format(self)

employees/forms.py
from django import forms
from .models import Employee

class EmployeeForm(forms.ModelForm):
	first_name = forms.CharField(max_length=80, required=False)
	last_name = forms.CharField(max_length=80, required=False)
	address_1 = forms.CharField(max_length=150, required=False)
	address_2 = forms.CharField(max_length=150, required=False)
	city = forms.CharField(max_length=30, required=False)
	state = forms.CharField(max_length=30, required=False)
	zipcode = forms.CharField(max_length=30, required=False)
	phone_1 = forms.CharField(max_length=30, required=False)
	phone_2 = forms.CharField(max_length=30, required=False)
	phone_3 = forms.CharField(max_length=30, required=False)
	phone_4 = forms.CharField(max_length=30, required=False)
	dob = forms.CharField(max_length=30, required=False)
	ssn = forms.CharField(max_length=30, required=False)
	department = forms.CharField(max_length=30, required=False)
	manager = forms.CharField(max_length=30, required=False)
	Salary = forms.CharField(max_length=30, required=False)
	
	class Meta:
		model = Employee
		fields = '__all__'

employees/views.py
from .models import Employee
from django.views import generic
from django.contrib.auth.models import User
import random
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin


# Create your views here.
class IndexView(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
	template_name = 'employees/employeeList.html'
	context_object_name = 'employees'
	paginate_by = 62
	permission_required = 'employees.view_employee'

	def get_queryset(self):
		if self.request.method == 'GET' and self.request.GET:
			if 'first_name' in self.request.GET:
				if self.request.GET['first_name']:
					searchtxt = self.request.GET.get('first_name', None)
					return Employee.objects.filter(first_name__icontains=searchtxt)

				if self.request.GET['last_name']:
					searchtxt_2 = self.request.GET.get('last_name', None)
					return Employee.objects.filter(last_name__icontains=searchtxt_2)

				else:
					return Employee.objects.order_by('id')

		else:
			return Employee.objects.order_by('id')

	
	

class DetailView(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):
	model = Employee
	template_name = 'employees/detail.html'
	permission_required = 'employees.view_employee'
	

class UpdateView(PermissionRequiredMixin, generic.UpdateView):
	model = Employee
	fields = '__all__'
	success_url = '/employeeList/'
	permission_required = 'employees.change_employee'
	
		
class CreateView(PermissionRequiredMixin, generic.CreateView):
	model = Employee
	fields = '__all__'
	template_name_suffix = '_create_form'
	success_url = '/employeeList/'
	permission_required = 'employees.add_employee'

	def form_valid(self, form):
		uname = 'temp' + str(random.randint(1,10000))
		usr = User.objects.create_user(uname, email=None, password='password1234')
		usr.first_name = self.request.POST['first_name']
		usr.last_name =  self.request.POST['last_name']
		usr.username = uname + usr.last_name
		usr.is_staff = True
		usr.save()

		return super(CreateView, self).form_valid(form)




class DeleteView(PermissionRequiredMixin, generic.DeleteView):
	model = Employee
	success_url = '/employeeList/'
	permission_required = 'employees.delete_employee'
						

employees/templates/employees/detail.html
{% extends 'basic.html' %}
{% block content %}
	<h1>{{ employee.last_name }}, {{ employee.first_name }}</h1>
	<div style="background-color: #191924; padding: 50px 25px">
		<div class="container">
		<div class="row">
			
			<div class="col-sm">
				<ul class="list-group">
					<li class="list-group-item">{{ employee.first_name }}</li>
					<li class="list-group-item">{{ employee.address_1 }}</li>
					<li class="list-group-item">{{ employee.city }}</li>
					<li class="list-group-item">{{ employee.zipcode }}</li>
					<li class="list-group-item">{{ employee.phone_2 }}</li>
					<li class="list-group-item">{{ employee.ssn }}</li>
					<li class="list-group-item">{{ employee.manager }}</li>
				</ul>
			</div>
			<div class="col-sm">
				<ul class="list-group">
					<li class="list-group-item">{{ employee.last_name }}</li>
					<li class="list-group-item">{{ employee.address_2 }}</li>
					<li class="list-group-item">{{ employee.state }}</li>
					<li class="list-group-item">{{ employee.phone_1 }}</li>
					<li class="list-group-item">{{ employee.dob }}</li>
					<li class="list-group-item">{{ employee.department }}</li>
					<li class="list-group-item">{{ employee.salary }}</li>
				</ul>
			</div>
			
		</div>
		<div class="row" style="padding-top: 10px">
			<div class="col-sm">
				<a href="{% url 'employees:update' employee.id %}" class="btn btn-danger">Edit</a>
				<a href="{% url 'employees:employeeList' %}" class="btn btn-danger">Employee List</a>
				<a href="{% url 'employees:delete' employee.id %}" class="btn btn-danger">DELETE</a>
			</div>
		</div>
	</div>
</div>
{% endblock %}

employees/templates/employees/employeeList.html
{% extends 'basic.html'  %}

{% block content %}

	<div class="page-header">
		<h1>Employee List</h1>
		<div class="row" style="margin-top: 35px">
		<div class="col">
			<a href="{% url 'index' %}" class="btn btn-outline-info" style="margin-bottom: 15px">Home</a>
			<a href="{% url 'logout' %}" class="btn btn-outline-info" style="margin-bottom: 15px">Logout</a>
		</div>
		<div class="col">
			<form method="GET">
				{% csrf_token %}
				<input type="text" name="first_name" placeholder="First Name">
				<input type="text" name="last_name" placeholder="Last Name">
				<button type="submit" class="btn btn-outline-danger">Search</button>
			</form>
		</div>
	</div>
	</div>
	<table class="table" style="background-color: #330000;">
		<thead style="color: #237BA0;">
			<tr>
				<th scope="col">Employee ID</th>
				<th scope="col">First Name</th>
				<th scope="col">Last Name</th>
				<th scope="col">City</th>
				<th scope="col">State</th>
			</tr>	
		</thead>
		<tbody>
			{% for employee in employees.all %}
			<tr>
				<th class="row"><a href="{% url 'employees:detail' employee.id %}">{{ employee.id }}</a></th>
				<td><a href="{% url 'employees:detail' employee.id %}">{{ employee.first_name }}</a></td>
				<td><a href="{% url 'employees:detail' employee.id %}">{{ employee.last_name }}</a></td>
				<td><a href="{% url 'employees:detail' employee.id %}">{{ employee.city }}</a></td>
				<td><a href="{% url 'employees:detail' employee.id %}">{{ employee.state }}</a></td>
			</tr>
			{% endfor %}
		</tbody>
	</table>

{% endblock %}

employees/templates/employees/employee_confirm_delete.html
{% extends 'basic.html' %}
{% block content %}
	<form method="POST">
		{% csrf_token %}
		<p>ARE YOU SURE YOU WANT TO DELETE {{ employee.last_name }}, {{ employee.first_name }}??</p>
		<button type="submit" class="btn btn-danger">Confirm</button>
	</form>

	{% endblock %}

employees/templates/employees/employee_create_form.html
{% extends 'basic.html' %}

{% block content %}
	<h1>Create a new employee!</h1>
		<div class="form-group" style="background: #191924">
			<form method="POST">
				{% csrf_token %}
				<table>
					{% for field in form %}		
						<tr class="row">
							<td class="col">{{ field.label_tag }}</td>
							<td class="col"> {{ field }}</td>
							<td>{{ field.errors }}</td>
						</tr>
					{% endfor %}
				</table>
				<button class="btn btn-danger btn-lg" type="submit">Save</button>
			</form>
		</div>
{% endblock %}

employees/templates/employees/employee_form.html
{% extends 'basic.html' %}

{% block content %}
	<h1>{{ employee.last_name }}, {{ employee.first_name }} ID: {{ employee.id }}</h1>
		
		<form method="POST" action="editEmployee">
			{% csrf_token %}
			<div class="form-group" style="background: #191924;">
				<table style="margin: 20px 15px">
				{% for field in form %}		
					<tr class="row">
						<td class="col">{{ field.label_tag }}</td>
						<td class="col"> {{ field }}</td>
						<td>{{ field.errors }}</td>
					</tr>
				{% endfor %}
				</table>
				<button class="btn btn-danger btn-lg" type="submit">Update</button>
			</div>
		</form>
{% endblock %}